language:
- c
os:
- osx
- linux
compiler:
- clang
- gcc
addons:
  apt:
    packages:
    - gcc-multilib
script: make test
notifications:
  email: false
  slack:
<<<<<<< HEAD
    secure: EuUu7q4IdMzLgpNL4EBegL48XK7eUxdME2vkCqiwwFOCvv86FMaIS/gLz/5/53xP7/z+Lf2aIWWXXshC6UaPWwirc1EPRCcCGWQNkUX8MMr01829cDhp7Zs33+HQalpI4WJbfIyS13xipBEMYLLcVU8W5/nYeA2/54livkPQTKHKhBOZBl2WzsKl1TOSHLqj5l2IvPhGS7pQdvf/siE/JDolenDVdEMuNFVb9KuKIjW192AQ4Mug5XdLSuAxokAW7ot1KHBHiWDdzMdG3KposWKjrL7RrTvFyrkHzleDVoDbUCKkJV/XYe3RSyQj+0jo+4AUbXkr3AdbBEq+DeeiQNYg2GN12D0Ku8hB60GOYkJNKYLvozJwemx74wIYXImtzTtlcTtKH7P7J9HgMxJb0OZrUkLVHfReOKSgzqrXjNSRuy2sZWCB4vsyP80UP8DKvb85yWm+S4yGgrzGsQUfBM3LS6wU/vrAT5ALVRAmOCmlBkvFkrgPBpKwgU7sXMbZ4PaWJFi1ybb/IUblVgDxLBRp3vwd6uBVk2OKhghMbcXvdxDC3XImYV2GSDyTScNGiC/ohEns01tjV716QVxaIPObNzQBSgJyC7CovxIxL7Xk5raOR2Lwalt52dNo7F6ee2uLhRPmZgzw9BNZ5J0wnWPVCDq8cr9WsPi4Y8E5+II=
=======
    secure: jES6YIcmcis3UhzhctAiEgIbWOB8XV5H4Ugm23h0uzU8ZcoUr7zIxsyY62iOk8vI2z9sPnACWU0ChJm66HnATzl5uaYYWpiDaV3kXRy+zpvCx0kt4ztmlgp80t2pgIxV3stPOY0oeI+yBnFJyet2PPOKNWW/3uDBR46cKCWS59c7sqjHlUJRE3oIDQ//NpC3mKDpdRKgjpVaD2YhP26rVL56BwD5LM3JvzljH2e8hYG9+LKogt4Uofs5usNRw57z6B/CokACjupWE1ayW2ziZ/CAmy1dImKkyFCUeLln065XtPHZnMdW+UrOoelMx/3PxeqMmwF47tg3bKsfDq0p6dlCaSfmPzHQcPgS/gtzOaw1iyxdR61nKBDLox6FMp+yARM9dKIlDAa+bqkfjlwy4EPuajjxamxjpiCTQtS+NvsM0yBTgghfG4eoGmIJLVsBqibPdqHx002cmEzGLcRoNotKca9bP3/NDbcoOswtdvgZPn36VGL2u7zwRRhizl25EfOOrSBe34W3X/UdBU0EC5qKSmBXTbrko19LsBdx6lN1oYosGRfLdK5maYVYKo1VHeeNqFuGp2GP91873Zuq8j8Dh45en/s4Nvg3B5QV3YnlIlBFDk/1DHZecKYN5XJE2UDKq3UtMGuwQE2WoCC8FQ+JjHhanuMufr1vtKhfqo4=
>>>>>>> cksystemsteaching/selfie-master
